export enum RitualType {
  NONE = '',
  ACCORD = 'ACCORD',
  CAERN = 'CAERN',
  DEATH = 'DEATH',
  MYSTIC = 'MYSTIC',
  PUNISHMENT = 'PUNISHMENT',
  RENOWN = 'RENOWN',
  SEASONAL = 'SEASONAL',
  MINOR = 'MINOR',
}
