name: 🪟 Build the application for Windows
env:
  app-name: wta-win32-x64
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: 💚 Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Build application
        run: npm run package:prod
      - name: Zip application
        run: |
          cd out/{{ env.app-name }}
          7z a ../../{{ env.app-name }}.zip .\*
      - uses: ncipollo/release-action@v1
        with:
          artifacts: '{{ env.app-name }}.zip'
